parameters:
    looptribe.formspatial.form.type.pointclass: Looptribe\FormSpatialBundle\Form\Type\PointType

services:
    looptribe.formspatial.form.type.point:
        class: %looptribe.formspatial.form.type.pointclass%
        tags:
            - { name: form.type, alias: point }
